Get http://localhost:3000/contacts HTTP/1.1

###
Get http://localhost:3000/contacts/6456d3380b18b4f6ade397bb HTTP/1.1

### PUT contact 
PUT http://localhost:3000/contacts/644d8d1044a9514f3fec9fe8 HTTP/1.1 
content-type: application/json

{
    "firstName": "Utibe",
    "lastName": "Omachona",
    "email": "princessutibe700@test.com",
    "favoriteColor": "Blue & Pink",
    "birthday": "22/04/1995"
  }

###
### Create contact 
POST http://localhost:3000/contacts HTTP/1.1 
content-type: application/json

{
"firstName":"Don", 
"lastName":"Jinee", 
"email":"don@test.com", 
"favoriteColor":"Blue", 
"birthday":"27/04/2000"
}


### View all contacts
Get https://contacts-zwae.onrender.com/contacts HTTP/1.1 

### View specific contact
Get https://contacts-zwae.onrender.com/contacts/6456d9ba0690b00ecb971823 HTTP/1.1

### Create contact 
POST http://contacts-zwae.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
"firstName":"Don", 
"lastName":"Jeffs", 
"email":"donj@test.com", 
"favoriteColor":"Eminem", 
"birthday":"27/04/2000"
}

### Update Contact
PUT http://contacts-zwae.onrender.com/contacts/644d8d1044a9514f3fec9fe8 HTTP/1.1 
content-type: application/json

{
    "firstName": "Utibe",
    "lastName": "Omachona",
    "email": "utyoncee@test.com",
    "favoriteColor": "Blue & Pink",
    "birthday": "22/04/1995"
  }

### Delete contact
DELETE  https://contacts-zwae.onrender.com/contacts/6456e7f23adce1f3ff83d3c8 HTTP/1.1